version: '3'
services:
  mysql-docker-container:
    image: 'mysql:latest'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_DATABASE=powerst_db
    ports:
      - "3306:3306"
  spring-jpa-app-container:
    #image: 'shtokala/app:vers1'
    image: spring-myapp
    ports:
      - "9966:9966"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-docker-container:3306/powerst_db?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    depends_on:
      - mysql-docker-container